### ISSUE TITLE
404 on Vercel website linked on Repo

### ISSUE THREAD

**Issue by ToasterUwU** [HuakunShen/git-skyline#6]
Found this gem while looking for an alternative since the offificial skyline is now dead in the water it seems. 

"The lights are out for now. Maybe they will turn back on again someday"

Looks really cool on paper, but i can test it or anything since the link on the right side of the page of the repo (the linked homepage) just gives a 404 error. I tried the others in deployments, but they are all either 404 errors or broken.

If its because you need to pay for this and dont want to spend the money, i understand, but please remove the broken links in that case and make a disclaimer.

**Comment by HuakunShen** [comment]
Forgot to update that link. The link is https://git-skyline.huakun.tech/
Thank you for you interest.
