### ISSUE TITLE
Base for Printable file

### ISSUE THREAD

**Issue by enisn** [HuakunShen/git-skyline#7]
How can I get 3D printable file?

**Comment by enisn** [comment]
Ok, found it

**Comment by enisn** [comment]
BTW you can create a base for STL file, it exports only bars and they're not connected on a single base

**Comment by HuakunShen** [comment]
Yeah, I knew this bug. Didn't have time to fix it, yet.

**Comment by HuakunShen** [comment]
@enisn Fixed. It now exports STL as a whole.

If you want to print it you may want to add a base, use `?&base=true` in the URL params.

See README for more info.
